{
            title: '日本',
            host: 'https://www5.javxxx.me/zh/',
            url: '/category/fyclass/page/fypage/,
            searchUrl: '/?s=**',
            class_parse: 'ul&&li;a&&Text;a&&href;.*/(.*?)/',
            class_exclude:"繁體中文|日本語",
            searchable: 2,
            quickSearch: 0,
            filterable: 0,
            headers: {
                'User-Agent': 'MOBILE_UA',
            },
            play_parse: true,
            lazy: '',
            limit: 6,
            推荐: '.videos-list;.videos-list&&a; a&&title; img&&data-lazy-src;.video-img&&Text;a&&href',
            double: true,
            一级: 'ul.vodlist li;a&&title;a&&data-original;.pic_text&&Text;a&&href',
            二级: {
                title: 'h2&&Text;.detail_list&&ul:eq(1)&&li&&a:eq(2)&&Text',
                img: '.vodlist_thumb&&data-original',
                desc: '.content_detail&&li:eq(1)&&Text;.detail_list&&ul:eq(1)&&li&&a&&Text;.detail_list&&ul:eq(1)&&li&&a:eq(1)&&Text;.detail_list&&ul:eq(1)&&li:eq(2)&&Text;.detail_list&&ul:eq(1)&&li:eq(3)&&Text',
                content: '.content_desc&&span&&Text',
                tabs: '.play_source_tab&&a',
                lists: '.content_playlist:eq(#id) li',
            },
            搜索: '*',
        },